In [139]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.cross_validation import train_test_split, cross_val_score

%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [115]:
df_titanic = pd.read_csv('data/train.csv')

In [116]:
def df_cleaner(df):
    df_titanic = df.copy()
    
    df_titanic['Sex'] = df_titanic['Sex'] == 'male'
    df_titanic[['C','Q','S']] = pd.get_dummies(df_titanic['Embarked'])
    df_titanic['Age'].fillna(df_titanic['Age'].median(), inplace=True)
    df_titanic['Cabin'].fillna('E', inplace=True)
    df_titanic['Cabin_level'] = df_titanic['Cabin'].apply(lambda x: x[0])
    df_titanic['Ticket_prefix'] = df_titanic['Ticket'].apply(lambda x: 'X' if len(x.split())==1 else x.split()[0])
    df_titanic['Title'] = df_titanic['Name'].apply(lambda x: x.split(',')[1].split()[0])
    df_titanic['Cabin_level'] = pd.Categorical(df_titanic['Cabin_level']).codes
    df_titanic['Ticket_prefix'] = pd.Categorical(df_titanic['Ticket_prefix']).codes
    df_titanic['Title'] = pd.Categorical(df_titanic['Title']).codes

    
    df_titanic.drop('Cabin',axis=1,inplace=True)
    df_titanic.drop('Embarked', axis=1, inplace=True)
    
    return df_titanic

In [120]:
df_clean = df_cleaner(df_titanic)

# Model1

In [121]:
y = df_clean['Survived'].values

In [127]:
X = df_clean.drop(['Survived','Name','Ticket'], axis=1) 

In [128]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

# Random Forest

In [129]:
RF_model = RandomForestClassifier(50)
RF_model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [131]:
cross_val_score(RF_model, X_train, y_train, cv=5, n_jobs=-1)

array([ 0.81666667,  0.78333333,  0.82352941,  0.80672269,  0.79661017])

In [132]:
RF_model.score(X_test, y_test)

0.76949152542372878

# AdaBossting 

In [135]:
AB_model = AdaBoostClassifier(learning_rate=0.1)
AB_model.fit(X_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=0.1, n_estimators=50, random_state=None)

In [137]:
cross_val_score(AB_model, X_train, y_train, cv=5)

array([ 0.8       ,  0.85833333,  0.78991597,  0.77310924,  0.81355932])

In [138]:
AB_model.score(X_test, y_test)

0.77966101694915257

# Gradient Boosting

In [140]:
GB_model = GradientBoostingClassifier()
GB_model.fit(X_train, y_train)

GradientBoostingClassifier(init=None, learning_rate=0.1, loss='deviance',
              max_depth=3, max_features=None, max_leaf_nodes=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [141]:
cross_val_score(GB_model, X_train, y_train, cv=5)

array([ 0.83333333,  0.86666667,  0.83193277,  0.77310924,  0.81355932])

In [142]:
GB_model.score(X_test, y_test)

0.78644067796610173